// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/appwrite/article': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/appwrite/article').default>>>>
    }
    '/api/back4app/article': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/back4app/article').default>>>>
    }
    '/api/mongo/article': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/mongo/article').default>>>>
    }
    '/api/mysql/article': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/mysql/article').default>>>>
    }
    '/api/nhost/article': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/nhost/article').default>>>>
    }
    '/api/postgres/article': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/postgres/article').default>>>>
    }
    '/api/sqlite/article': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/sqlite/article').default>>>>
    }
    '/api/supabase/:table': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/supabase/[table]').default>>>>
    }
    '/api/supabase/tables': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/supabase/tables').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/nuxt/dist/core/runtime/nitro/handlers/renderer').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
  }
}
export {}